---
extends: stylelint-config-standard
plugins: 
  - stylelint-order
  - stylelint-scss
rules: 
  custom-property-empty-line-before:
    - never
    - ignore: after-comment
  indentation: 4
  order/properties-alphabetical-order: 
    - true
    - severity: warning

