---
extends: stylelint-config-standard
plugins: 
  - stylelint-order
  - stylelint-scss
rules: 
  custom-property-empty-line-before:
    - never
    - ignore: after-comment
  declaration-block-semicolon-space-before: never-single-line
  indentation: 4
  no-descending-specificity: true
  order/properties-alphabetical-order: 
    - true
    - severity: warning
  selector-list-comma-newline-after: null
  selector-list-comma-newline-before: always
  selector-list-comma-space-after: always
  selector-list-comma-space-before: never-single-line

